sudo: false
language: java
jdk: openjdk11

env:
  global:
   - SONAR_TOKEN: "0439543f5777663d7fa0c8ea532de59709ab48c0"

addons:
    sonarcloud:
      organization: "akshay7671"
      token:
        secure: $SONAR_TOKEN

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
